#!/usr/bin/env python3
"""Generates the firmware's bitmap font table from a BDF font.

Usage: tools/bdf_to_font.py tools/fonts/5x7.bdf > Drivers/BSP/Components/graphics/font_5x7.cpp

The source font is the X11 misc-fixed 5x7 font, which is public domain
("Public domain font. Share and enjoy.").

Output covers printable ASCII (0x20-0x7E). The degree sign (U+00B0) is stored
in the otherwise unused 0x7F slot, since the firmware's text is plain ASCII.
Each glyph is `width` bytes, one per column, left to right; bit 0 of each
byte is the top row.
"""
import sys

DEGREE_SLOT = 0x7F


def parse_bdf(path):
    glyphs = {}
    ascent = width = height = None
    with open(path) as f:
        lines = iter(f.read().splitlines())
    for line in lines:
        if line.startswith("FONTBOUNDINGBOX"):
            _, width, height, _, _ = line.split()
            width, height = int(width), int(height)
        elif line.startswith("FONT_ASCENT"):
            ascent = int(line.split()[1])
        elif line.startswith("STARTCHAR"):
            encoding = bbx = None
            for line in lines:
                if line.startswith("ENCODING"):
                    encoding = int(line.split()[1])
                elif line.startswith("BBX"):
                    bbx = [int(v) for v in line.split()[1:]]
                elif line == "BITMAP":
                    rows = []
                    for line in lines:
                        if line == "ENDCHAR":
                            break
                        rows.append(int(line, 16))
                    glyphs[encoding] = (bbx, rows)
                    break
    return width, height, ascent, glyphs


def to_columns(glyph, width, height, ascent):
    (w, h, xoff, yoff), rows = glyph
    row_bits = ((w + 7) // 8) * 8
    columns = [0] * width
    for i, row in enumerate(rows):
        cell_row = ascent - yoff - h + i
        for j in range(w):
            if row & (1 << (row_bits - 1 - j)):
                cell_col = xoff + j
                if not (0 <= cell_col < width and 0 <= cell_row < height):
                    raise ValueError("glyph pixel outside the cell")
                columns[cell_col] |= 1 << cell_row
    return columns


def main():
    width, height, ascent, glyphs = parse_bdf(sys.argv[1])
    slots = {code: code for code in range(0x20, 0x7F)}
    slots[DEGREE_SLOT] = 0xB0

    print("// Generated by tools/bdf_to_font.py from tools/fonts/5x7.bdf (X11 misc-fixed")
    print("// 5x7, public domain). Do not edit by hand.")
    print('#include "font_5x7.hpp"')
    print()
    print("namespace")
    print("{")
    print(f"constexpr std::uint8_t kGlyphs[] = {{")
    for slot, code in sorted(slots.items()):
        columns = to_columns(glyphs[code], width, height, ascent)
        # Named rather than printed: a comment ending in a backslash would
        # continue onto the next line and swallow that glyph.
        names = {DEGREE_SLOT: "degree sign", 0x20: "space", 0x5C: "backslash"}
        name = names.get(slot, chr(code))
        values = ", ".join(f"0x{c:02X}" for c in columns)
        print(f"    {values}, // 0x{slot:02X} {name}")
    print("};")
    print("} // namespace")
    print()
    print(f"const Font kFont5x7{{{width}, {height}, 0x20, 0x{DEGREE_SLOT:02X}, kGlyphs}};")


if __name__ == "__main__":
    main()
